version: "3.8"

services:
  # Next.js container
  next-app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    networks:
      default:
        aliases:
          - nextjs
    working_dir: /app
    environment:
      NODE_ENV: production
    command: ["sh", "-c", "yarn run start"]

  # Node container for GraphQL
  graphql-node:
    build:
      context: ./graphql
      dockerfile: Dockerfile.prod
    ports:
      - 4000:4000
    networks:
      default:
        aliases:
          - graphql
    working_dir: /var/www
    environment:
      NODE_ENV: production
    command: ["sh", "-c", "yarn run start"]

  # Redis container
  redis:
    image: redis:latest
    ports:
      - 6379:6379
