FROM node:22-bookworm-slim AS node-dev

RUN apt-get update \
    && apt-get -y install \
    make \
    git \
    openssh-client \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=development

WORKDIR /var/www

COPY yarn.lock .
COPY package.json .

RUN yarn install

COPY . .

CMD ["yarn", "run", "dev"]

EXPOSE 4000