name: Run Tests and Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to app directory
        run: cd ./app

      - name: Install dependencies
        run: yarn install
        working-directory: ./app

      - name: Run ESLint
        run: yarn lint
        working-directory: ./app

      - name: Annotate ESLint problems
        if: ${{ failure() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint.sarif

  test:
    name: Run Vitest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
