name: Deploy Storybook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to app directory
        run: cd app

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Verify static assets
        working-directory: ./app
        run: ls -R public

      - name: Extract repository name
        run: echo "BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Check BASE_PATH
        run: echo "BASE_PATH=$BASE_PATH"

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ./app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/storybook-static
